url: "https://chion.me" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Chion Reverie" # the name of your site, e.g. ACME Corp.
repository: "https://github.com/ChionReverie/chion.me"

collections:
  characters:
    output: true

toc:
  max_level: 3

plugins:
  - jekyll-toc
  - jekyll-sitemap

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.MD
  - TODO.MD